<?php

/**
 * BaseHousingResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $num_rooms
 * @property integer $square_footage
 * @property string $address_1
 * @property string $address_2
 * @property string $city
 * @property string $state
 * @property string $zip
 * @property string $phone_1
 * @property string $phone_2
 * @property string $email
 * 
 * @method integer         getNumRooms()       Returns the current record's "num_rooms" value
 * @method integer         getSquareFootage()  Returns the current record's "square_footage" value
 * @method string          getAddress1()       Returns the current record's "address_1" value
 * @method string          getAddress2()       Returns the current record's "address_2" value
 * @method string          getCity()           Returns the current record's "city" value
 * @method string          getState()          Returns the current record's "state" value
 * @method string          getZip()            Returns the current record's "zip" value
 * @method string          getPhone1()         Returns the current record's "phone_1" value
 * @method string          getPhone2()         Returns the current record's "phone_2" value
 * @method string          getEmail()          Returns the current record's "email" value
 * @method HousingResource setNumRooms()       Sets the current record's "num_rooms" value
 * @method HousingResource setSquareFootage()  Sets the current record's "square_footage" value
 * @method HousingResource setAddress1()       Sets the current record's "address_1" value
 * @method HousingResource setAddress2()       Sets the current record's "address_2" value
 * @method HousingResource setCity()           Sets the current record's "city" value
 * @method HousingResource setState()          Sets the current record's "state" value
 * @method HousingResource setZip()            Sets the current record's "zip" value
 * @method HousingResource setPhone1()         Sets the current record's "phone_1" value
 * @method HousingResource setPhone2()         Sets the current record's "phone_2" value
 * @method HousingResource setEmail()          Sets the current record's "email" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHousingResource extends Resource
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('housing_resource');
        $this->hasColumn('num_rooms', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('square_footage', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address_1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address_2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('state', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('zip', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('phone_1', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('phone_2', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}