<?php

/**
 * BaseResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $transaction_type
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()           Returns the current record's "user_id" value
 * @method string      getTransactionType()  Returns the current record's "transaction_type" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method Resource    setUserId()           Sets the current record's "user_id" value
 * @method Resource    setTransactionType()  Sets the current record's "transaction_type" value
 * @method Resource    setUser()             Sets the current record's "User" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('transaction_type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}