<?php

/**
 * BaseInfoResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $abstract
 * @property string $keywords
 * @property string $url
 * 
 * @method clob         getAbstract() Returns the current record's "abstract" value
 * @method string       getKeywords() Returns the current record's "keywords" value
 * @method string       getUrl()      Returns the current record's "url" value
 * @method InfoResource setAbstract() Sets the current record's "abstract" value
 * @method InfoResource setKeywords() Sets the current record's "keywords" value
 * @method InfoResource setUrl()      Sets the current record's "url" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfoResource extends Resource
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('info_resource');
        $this->hasColumn('abstract', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}