<?php

/**
 * BaseResourceParticipant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $participant_id
 * @property integer $resource_id
 * 
 * @method integer             getParticipantId()  Returns the current record's "participant_id" value
 * @method integer             getResourceId()     Returns the current record's "resource_id" value
 * @method ResourceParticipant setParticipantId()  Sets the current record's "participant_id" value
 * @method ResourceParticipant setResourceId()     Sets the current record's "resource_id" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResourceParticipant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource_participant');
        $this->hasColumn('participant_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('resource_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}