<?php

/**
 * BaseTimeResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property integer $num_volunteers
 * 
 * @method timestamp    getStartDate()      Returns the current record's "start_date" value
 * @method timestamp    getEndDate()        Returns the current record's "end_date" value
 * @method integer      getNumVolunteers()  Returns the current record's "num_volunteers" value
 * @method TimeResource setStartDate()      Sets the current record's "start_date" value
 * @method TimeResource setEndDate()        Sets the current record's "end_date" value
 * @method TimeResource setNumVolunteers()  Sets the current record's "num_volunteers" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimeResource extends Resource
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('time_resource');
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('num_volunteers', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}