<?php

/**
 * BaseContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resource_id
 * @property string $resource_type
 * @property string $email
 * @property string $name
 * @property string $phone
 * @property clob $notes
 * 
 * @method integer getResourceId()    Returns the current record's "resource_id" value
 * @method string  getResourceType()  Returns the current record's "resource_type" value
 * @method string  getEmail()         Returns the current record's "email" value
 * @method string  getName()          Returns the current record's "name" value
 * @method string  getPhone()         Returns the current record's "phone" value
 * @method clob    getNotes()         Returns the current record's "notes" value
 * @method Contact setResourceId()    Sets the current record's "resource_id" value
 * @method Contact setResourceType()  Sets the current record's "resource_type" value
 * @method Contact setEmail()         Sets the current record's "email" value
 * @method Contact setName()          Sets the current record's "name" value
 * @method Contact setPhone()         Sets the current record's "phone" value
 * @method Contact setNotes()         Sets the current record's "notes" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contact');
        $this->hasColumn('resource_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('resource_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('notes', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}