<?php

/**
 * BaseMaterialResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quantity
 * 
 * @method integer          getQuantity() Returns the current record's "quantity" value
 * @method MaterialResource setQuantity() Sets the current record's "quantity" value
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaterialResource extends Resource
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('material_resource');
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}