sf_guard_group:
  url: /users
  param: { module: users, action: index }

sf_guard_permission:
  url: /users
  param: { module: users, action: index }

sf_guard_user:
  url: /users
  param: { module: users, action: index }

users:
  url: /users
  param: { module: users, action: index }
statistics:
  url:  /
  param: { module: statistics, action: index }
  
# default rules
homepage:
  url:   /
  param: { module: statistics, action: index }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
