<?php

/**
 * PluginsfFbConnectGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFbConnectGuardUserTable extends Doctrine_Table
{
  public function getSfGuardUserByFbId( $fbId )
  {
    $q = Doctrine::getTable('sfGuardUser')
        ->createQuery('u')
        ->innerJoin('u.FacebookUser fu')
        ->where('fu.facebook_id = ?', $fbId);
    return $q->fetchOne();
  }
  
  public function createFbUser( $fbId )
  {
    $user = new sfGuardUser();
    $user['FacebookUser']['facebook_id'] = $fbId;
    $user['username'] =  $fbId ;
    $user->save();
    return $user->getId();
  }
  
  public function linkSfFbUser( $fbId, $userId )
  {
    $fb = new sfFbConnectGuardUser();
    $fb->setUserId( $userId );
    $fb->setFbUid( $fbId );
    $fb->save();
  }
  
  public function isUserFbConnected( $userId )
  {
    return $this->createQuery()->where('user_id = ?', $userId)->count() > 0;
  }
}