<?php

/**
 * Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    skeleton
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Resource extends BaseResource
{
  public function preInsert($event)
  {
    if (!array_filter($this['address_1'], $this['address_2'], $this['city'], $this['state'], $this['zip'])) 
    {
      $this['address_1'] = $this['User']['address_1'];
      $this['address_2'] = $this['User']['address_2'];
      $this['city'] = $this['User']['city'];
      $this['state'] = $this['User']['state'];
      $this['zip'] = $this['User']['zip'];
    }
  }  
}
