all:
  email:
    from:    contact@donatenashville.org
    subjects:
      need_time_creation:   Need for Time entry created at donatenashville.org
      need_stuff_creation:  Need for Stuff entry created at donatenashville.org
      have_stuff_creation:  Have Stuff entry created at donatenashville.org
