prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none
      transport:
        class:   Swift_MailTransport

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true
  mailer:
    param:
<?php if (file_exists(dirname(__FILE__).'/../../../config/mailer.yml')): ?>
<?php include(dirname(__FILE__).'/../../../config/mailer.yml') ?>
<?php else: ?>
      transport:
        class:  Swift_MailTransport
<?php endif ?>