have:
  url:   /donate
  param: { module: donation, action: index }

have_time:
  url:   /donate/time
  param: { module: time, action: have }
  
have_stuff:
  url:   /donate/stuff
  param: { module: time, action: stuff }

need:
  url:   /need
  param: { module: need, action: index }

need_time:
  url:   /need/time
  param: { module: time, action: need }

need_stuff:
  url:   /need/stuff
  param: { module: stuff, action: need }

need_housing:
  url:   /need/place
  param: { module: resource, action: housing }

need_money:
  url:   /need/money
  param: { module: resource, action: money }


# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
