donate:
  url:   /donate
  param: { module: donation, action: index }

donate_time:
  url:   /donate/time
  param: { module: donation, action: time }
  
donate_material:
  url:   /donate/stuff
  param: { module: donation, action: material }

need:
  url:   /need
  param: { module: need, action: index }

need_time:
  url:   /need/time
  param: { module: need, action: time }
  
need_material:
  url:   /need/stuff
  param: { module: need, action: material }

need_housing:
  url:   /need/place
  param: { module: need, action: housing }

need_money:
  url:   /need/money
  param: { module: need, action: money }


# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
