have:
  url:   /have
  param: { module: resource, action: have }

have_time:
  url:   /have/time
  param: { module: time, action: have }

have_stuff:
  url:   /have/stuff
  param: { module: stuff, action: have }

need:
  url:   /need
  param: { module: resource, action: need }

# Create time resource routes
add_need_time:
  class:  sfRequestRoute
  url:   /need/time/add
  param: { module: time, action: addNeed }
  requirements:
    sf_method: [get]
add_need_time_create:
  class:  sfRequestRoute
  url:   /need/time/add
  param: { module: time, action: addNeedCreate }
  requirements:
    sf_method: [post]

need_stuff:
  url:   /need/stuff
  param: { module: stuff, action: need }

# Create stuff resource routes
add_need_stuff:
  class:  sfRequestRoute
  url:   /need/stuff/add
  param: { module: stuff, action: addNeed }
  requirements:
    sf_method: [get]
add_need_stuff_create:
  class:  sfRequestRoute
  url:   /need/stuff/add
  param: { module: stuff, action: addNeedCreate }
  requirements:
    sf_method: [post]
  
need_housing:
  url:   /need/place
  param: { module: resource, action: housing }

need_money:
  url:   /need/money
  param: { module: resource, action: money }

time_list:
  url:   /time/list
  param: { module: resource, action: timeList }

stuff_list:
  url:   /stuff/list
  param: { module: resource, action: stuffList }

need_time_list:
  url:   /time/list
  param: { module: resource, action: timeList, type: need }

have_time_list:
  url:   /time/list
  param: { module: resource, action: timeList, type: have }

need_stuff_list:
  url:   /stuff/list
  param: { module: resource, action: stuffList, type: need }

have_stuff_list:
  url:   /stuff/list
  param: { module: resource, action: stuffList, type: have }

need_stuff_create:
  url:   /need/stuff/create
  param: { module: stuff, action: haveCreate }

have_stuff_create:
  url:   /have/stuff/create
  param: { module: stuff, action: needCreate }
  
stuff_match:
  class:    sfDoctrineRoute
  url:      /stuff/:id/match
  options:  { type: object, model: StuffResource }
  param:    { module: stuff, action: match }

time_match:
  class:    sfDoctrineRoute
  url:   /time/:id/match
  options:  { type: object, model: StuffResource }
  param: { module: time, action: match }

# User management-related routes
user_auth:
  url:   /auth/:token
  param: { module: user, action: authenticate }
user_resource:
  url:   /user/resource
  param: { module: user, action: resource }

homepage:
  url:   /
  param: { module: default, action: index }
