have:
  url:   /have
  param: { module: resource, action: have }

have_time:
  url:   /have/time
  param: { module: time, action: have }

have_time_create:
  url:   /have/time/create
  param: { module: time, action: haveCreate }

have_stuff:
  url:   /have/stuff
  param: { module: stuff, action: have }

need:
  url:   /need
  param: { module: resource, action: need }

need_time:
  url:   /need/time
  param: { module: time, action: need }

need_time_create:
  url:   /need/time/create
  param: { module: time, action: needCreate }

need_stuff:
  url:   /need/stuff
  param: { module: stuff, action: need }

need_housing:
  url:   /need/place
  param: { module: resource, action: housing }

need_money:
  url:   /need/money
  param: { module: resource, action: money }

time_list:
  url:   /time/list
  param: { module: resource, action: timeList }

stuff_list:
  url:   /stuff/list
  param: { module: resource, action: stuffList }

need_time_list:
  url:   /time/list
  param: { module: resource, action: timeList, type: need }

have_time_list:
  url:   /time/list
  param: { module: resource, action: timeList, type: have }

need_stuff_list:
  url:   /stuff/list
  param: { module: resource, action: stuffList, type: need }

have_stuff_list:
  url:   /stuff/list
  param: { module: resource, action: stuffList, type: have }

user_auth:
  url:   /auth/:token
  param: { module: user, action: authenticate }

user_resource:
  url:   /authenticate
  param: { module: user, action: resource }

need_time_create:
  url:   /time/create
  param: { module: time, action: needCreate, type: need }

need_stuff_create:
  url:   /need/stuff/create
  param: { module: stuff, action: haveCreate }

have_stuff_create:
  url:   /have/stuff/create
  param: { module: stuff, action: needCreate }
  


# default rules
homepage:
  url:   /
  param: { module: default, action: index }
