default:
  http_metas:
    content-type: text/html

  metas:
    title:        DonateNashville.org
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:     [reset.css, text.css, 960.css, main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
