default:
  http_metas:
    content-type: text/html

  metas:
    title:        Home | DonateNashville.org
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:     [reset.css, text.css, 960.css, base.css, forms.css, donatenashville.css, ie7.css: {condition: lte IE 7}]

  javascripts:    [app/donateNashville.js]

  has_layout:     true
  layout:         layout
