<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{

  /**
   * We don't really reqiure a password for a new user, but we do use
   * it to generate a hash. So, we set one randomly if we have none.
   */
  public function preSave($event)
  {
    if (!$this->password)
    {
      $this->password = md5($this->created_at + rand(0, 1000));
    }

    // we're not using both username and email, so user the email_address
    if (!$this->username)
    {
      $this->username = $this->email_address;
    }
  }
}