all:
  TinyMce:
    config:
      plugins: 'pagebreak, fullscreen, advimage'
      fullscreen_new_window: true
      relative_urls: false
      theme_advanced_buttons1: "bold, italic, underline, bullist, numlist, outdent, indent, blockquote, justifyleft, justifycenter, justifyright, link, unlink, image, separator, undo, redo"
      theme_advanced_buttons2: 'hr,removeformat,visualaid,separator,sub,sup,separator,charmap, fullscreen, pagebreak, formatselect, styleselect, code'
      theme_advanced_buttons3: ""
      extended_valid_elements: 'img[style|class|src|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name]'

    ### For Custom Styles: ###
      theme_advanced_styles: 'Caption=caption'
      content_css: '%web_root%/css/tinymce-custom-styles.css'

    ### For Kae's File Manager: ###
      # file_browser_callback: 'kfm_for_tiny_mce'
      # kfm_web_dir: '%web_root%/kfm'