<h1>Terms of Use</h1>

<ol class="terms-of-service">
  <li>
    <h4>ACCEPTANCE OF TERMS</h4>


    <p>Donate Nashville provides a means to connect people providing services or goods with people in need, (referred to hereafter as "the Service") subject to the following Terms of Use ("TOU"). By using the Service in any way, you are agreeing to comply with the TOU. In addition, when using particular Donate Nashville services, you agree to abide by any applicable posted guidelines for all Donate Nashville services, which may change from time to time. Should you object to any term or condition of the TOU, any guidelines, or any subsequent modifications thereto or become dissatisfied with Donate Nashville in any way, your only recourse is to immediately discontinue use of Donate Nashville. Donate Nashville has the right, but is not obligated, to strictly enforce the TOU through self-help, community moderation, active investigation, litigation and prosecution.</p>
  </li>

  <li><h4>MODIFICATIONS TO THIS AGREEMENT</h4>

  <p>We reserve the right, at our sole discretion, to change, modify or otherwise alter these terms and conditions at any time. Such modifications shall become effective immediately upon the posting thereof. You must review this agreement on a regular basis to keep yourself apprised of any changes.</p>
  </li>

  <li><h4>CONTENT</h4>

  <p>You understand that all postings, messages, text, files, images, photos, video, sounds, or other materials ("Content") posted on, transmitted through, or linked from the Service, are the sole responsibility of the person from whom such Content originated. More specifically, you are entirely responsible for each individual item ("Item") of Content that you post, email or otherwise make available via the Service. You understand that Donate Nashville does not control, and is not responsible for Content made available through the Service, and that by using the Service, you may be exposed to Content that is offensive, indecent, inaccurate, misleading, or otherwise objectionable. Furthermore, the Donate Nashville site and Content available through the Service may contain links to other websites, which are completely independent of Donate Nashville. Donate Nashville makes no representation or warranty as to the accuracy, completeness or authenticity of the information contained in any such site. Your linking to any other webites is at your own risk. You agree that you must evaluate, and bear all risks associated with, the use of any Content, that you may not rely on said Content, and that under no circumstances will Donate Nashville be liable in any way for any Content or for any loss or damage of any kind incurred as a result of the use of any Content posted, emailed or otherwise made available via the Service. You acknowledge that Donate Nashville does not pre-screen or approve Content, but that Donate Nashville shall have the right (but not the obligation) in its sole discretion to refuse, delete or move any Content that is available via the Service, for violating the letter or spirit of the TOU or for any other reason.</p>
  </li>

<li><h4>THIRD PARTY CONTENT, SITES, AND SERVICES</h4> 

<p>The Donate Nashville site and Content available through the Service may contain people, services and content which are completely independent of Donate Nashville, including web sites, directories, servers, networks, systems, information and databases, applications, software, programs, products or services, and the Internet as a whole. Your interactions with organizations and/or individuals found on or through the Service, including donations, payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that Donate Nashville shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you understand and agree that Donate Nashville is under no obligation to become involved. In the event that you have a dispute with one or more other users, you hereby release Donate Nashville, its officers, employees, agents and successors in rights from claims, demands and damages (actual and consequential) of every kind or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to such disputes and / or our service.</p></li>

<li><h4>PRIVACY AND INFORMATION DISCLOSURE</h4> 


<p>No personal information will be disclosed by Donate Nashville unless explicitly authorized by you, via the normal operation of the Service. However, by using the Service, you acknowledge and agree that Donate Nashville may, in its sole discretion, preserve or disclose your Content, as well as your information, such as email addresses, IP addresses, timestamps, and other user information, if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: comply with legal process; enforce the TOU; respond to claims that any Content violates the rights of third-parties; respond to claims that contact information (e.g. phone number, street address) of a third-party has been posted or transmitted without their consent or as a form of harassment; protect the rights, property, or personal safety of Donate Nashville, its users or the general public.</p></li>


<li><h4>DISCLAIMER OF WARRANTIES</h4> 

<p>YOU AGREE THAT USE OF THE Donate Nashville SITE AND THE SERVICE IS ENTIRELY AT YOUR OWN RISK. THE Donate Nashville SITE AND THE SERVICE ARE PROVIDED ON AN "AS IS" OR "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND. ALL EXPRESS AND IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS ARE EXPRESSLY DISCLAIMED TO THE FULLEST EXTENT PERMITTED BY LAW. TO THE FULLEST EXTENT PERMITTED BY LAW, Donate Nashville DISCLAIMS ANY WARRANTIES FOR THE SECURITY, RELIABILITY, TIMELINESS, ACCURACY, AND PERFORMANCE OF THE Donate Nashville SITE AND THE SERVICE. TO THE FULLEST EXTENT PERMITTED BY LAW, Donate Nashville DISCLAIMS ANY WARRANTIES FOR OTHER SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON THE Donate Nashville SITE OR THE SITES OR SERVICE, OR ACCESSED THROUGH ANY LINKS ON THE Donate Nashville SITE. TO THE FULLEST EXTENT PERMITTED BY LAW, Donate Nashville DISCLAIMS ANY WARRANTIES FOR VIRUSES OR OTHER HARMFUL COMPONENTS IN CONNECTION WITH THE Donate Nashville SITE OR THE SERVICE. Some jurisdictions do not allow the disclaimer of implied warranties. In such jurisdictions, some of the foregoing disclaimers may not apply to you insofar as they relate to implied warranties.</p></li>

<li><h4>LIMITATIONS OF LIABILITY</h4>

<p>UNDER NO CIRCUMSTANCES SHALL Donate Nashville BE LIABLE FOR DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF Donate Nashville HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY ASPECT OF YOUR USE OF THE Donate Nashville SITE OR THE SERVICE, WHETHER THE DAMAGES ARISE FROM USE OR MISUSE OF THE Donate Nashville SITE OR THE SERVICE, FROM INABILITY TO USE THE Donate Nashville SITE OR THE SERVICE, OR THE INTERRUPTION, SUSPENSION, MODIFICATION, ALTERATION, OR TERMINATION OF THE Donate Nashville SITE OR THE SERVICE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF OTHER SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE Donate Nashville SITE OR THE SERVICE OR ANY LINKS ON THE Donate Nashville SITE, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE Donate Nashville SITE OR THE SERVICE OR ANY LINKS ON THE Donate Nashville SITE. THESE LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. In some jurisdictions, limitations of liability are not permitted. In such jurisdictions, some of the foregoing limitation may not apply to you.</p></li>

<li><h4>INDEMNITY</h4>

<p>You agree to indemnify and hold Donate Nashville, its officers, subsidiaries, affiliates, successors, assigns, directors, officers, agents, service providers, suppliers and employees, harmless from any claim or demand, including reasonable attorney fees and court costs, made by any third party due to or arising out of Content you submit, post or make available through the Service, your use of the Service, your violation of the TOU, your breach of any of the representations and warranties herein, or your violation of any rights of another.</p></li>

<?php slot('breadcrumbs', get_component('default', 'breadcrumbs')) ?>