<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RemoveContactIndexesMigration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('contact', 'contact_resource_id_resource_id');
    }

    public function down()
    {
        $this->createForeignKey('contact', 'contact_resource_id_resource_id', array(
             'name' => 'contact_resource_id_resource_id',
             'local' => 'resource_id',
             'foreign' => 'id',
             'foreignTable' => 'resource',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
    }
}