Resource:
  actAs:
    Timestampable:      []
    Locatable:
      fields:           [address_1, address_2, city, state, zip]
  columns:
    owner_id:
      type:             integer
      notnull:          true
    transaction_type:
      type:             enum
      notnull:          true
      values:           [need, have]
    title:
      type:             string(255)
      notnull:          true
    description:
      type:             clob
    privacy:
      type:             enum
      values:           [show_info, web_form]
      default:          true
    is_fulfilled:
      type:             boolean
      default:          false
    address_1:
      type:             string(255)
    address_2:             
      type:             string(255)
    city:
      type:             string(100)
    state:
      type:             string(100)
    zip:
      type:             string(100)
    phone_1:
      type:             string(100)
    phone_2:
      type:             string(100)
    email:
      type:             string(100)
  relations:
    User:
      class:            sfGuardUser
      local:            owner_id
      foreignAlias:     Resources
      onDelete:         CASCADE
      
TimeResource:
  inheritance:
    extends:            Resource
    type:               concrete
  columns:
    resource_date:
      type:             timestamp
      notnull:          true
    start_time:
      type:             time
      notnull:          true
    end_time:
      type:             time
    num_volunteers:
      type:             integer
    
StuffResource:
  inheritance:
    extends:            Resource
    type:               concrete
  columns:
    quantity:
      type:             integer
      default:          1

ResourceParticipant:
  columns:
    participant_id:
      type:             integer
      notnull:          true
    resource_id:
      type:             integer
      notnull:          true
  relations:
    
Contact:
  columns:
    resource_id:
      type:             integer
      length:           8
    email:
      type:             string
      length:           255
      notnull:          true
    name:
      type:             string
      length:           255
    phone:
      type:             string
      length:           100
    notes:
      type:             clob
  relations:
    Resource:
      local:            resource_id
      foreignAlias:     Contacts
      onDelete:         CASCADE
