Resource:
  actAs:
    Locatable:
      fields:             [address_1, address_2, city, state, zip]
  columns:
    owner_id:
      type:             integer(4)
      notnull:          true
    transaction_type:
      type:             enum
      notnull:          true
      values:           [need, have]
    title:
      type:             string(255)
      notnull:          true
    description:
      type:             clob
    show_contact_info:
      type:             boolean
      default:          true
    is_satisfied:
      type:             boolean
      default:          false
    address_1:
      type:             string(255)
    address_2:             
      type:             string(255)
    city:
      type:             string(100)
    state:
      type:             string(100)
    zip:
      type:             string(100)
    phone_1:
      type:             string(100)
    phone_2:
      type:             string(100)
    email:
      type:             string(100)
  relations:
    User:
      class:            sfGuardUser
      local:            owner_id
      foreignAlias:     Resoures
      onDelete:         CASCADE
      
TimeResource:
  inheritance:
    extends:            Resource
    type:               concrete
  columns:
    start_date:
      type:             timestamp
      notnull:          true
    end_date:
      type:             timestamp
      notnull:          true
    num_volunteers:
      type:             integer
    
StuffResource:
  inheritance:
    extends:            Resource
    type:               concrete
  columns:
    quantity:
      type:             integer
      default:          1

ResourceParticipant:
  columns:
    participant_id:
      type:             integer(4)
      notnull:          true
    resource_id:
      type:             integer(4)
      notnull:          true
  relations:
    