# Adds to the schema in sfDoctrineGuardPlugin
sfGuardUserProfile:
  actAs:
    Locatable:
      fields:          [address_1, address_2, city, state, zip]
  columns:
    user_id:
      type:            integer
      notnull:         true
    address_1:         string(255)
    address_2:         string(255)
    city:              string(100)
    state:             string(100)
    zip:               string(100)
    phone_1:           string(100)
    phone_2:           string(100)
    facebook_uid:      string(20)
    account_type:
      type:            enum
      default:         individual
      values:          [individual, shelter, nonprofit]
      notnull:         true
  indexes:
    facebook_uid_index:
      fields: [facebook_uid]
      unique: true
  relations:
    User:
      class:           sfGuardUser
      type:            one
      foreignType:     one
      local:           user_id
      foreignAlias:    Profile
      onDelete:        cascade
  options:
    symfony:
      filter:          false