# Adds to the schema in sfDoctrineGuardPlugin
sfGuardUser:
  actAs:
    Locatable:
      fields:             [address_1, address_2, city, state, zip]
  columns:
    address_1:             string(255)
    address_2:             string(255)
    city:                  string(100)
    state:                 string(100)
    zip:                   string(100)
    phone_1:               string(100)
    phone_2:               string(100)
    email:                 string(100)
    account_type:
      type:                enum
      default:             individual
      values:              [individual, shelter, nonprofit]
      notnull:             true
